name: Java CI with Maven and Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Set environment variable for GUSPRED_KEY
        env:
          GUSPRED_KEY: ${{ secrets.GUSPRED_KEY }}
        run: echo "GUSPRED_KEY is set"

      - name: Build with Maven and Run Tests
        env:
          GUSPRED_KEY: ${{ secrets.GUSPRED_KEY }}
        run: mvn clean install

      - name: Upload Code Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/index.html

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v1.0.0 # Użyj poprawnej wersji akcji
